services:
  app:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: node_js_project_front
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: unless-stopped  
    stdin_open: true
    tty: true
  db:
    env_file: .env
    image: postgres:15
    container_name: node_js_project_postgres_db
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres_data:
    driver: local